services:
  web:
    image: ghcr.io/koalixswitzerland/koalixcrm-dev-container:main
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
    environment:
      DJANGO_SETTINGS_MODULE: "projectsettings.settings.development_docker_sqlite_settings"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
