# Generated by Django 3.2.25 on 2024-10-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUserExtension', '0008_auto_20240329_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('xslfile', models.FileField(upload_to='xsl_files/')),
            ],
        ),
    ]
