# Generated by Django 3.2.25 on 2024-10-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUserExtension', '0009_xslfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xslfile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
